ARG BUILD_FROM=alpine:latest
FROM $BUILD_FROM

# update sources
RUN apk update

# shell-pack does run with nothing but busybox if it has to.
# comment out these packages for a "survival mode" container.
# some packages are attempted individually as they don't exist in ancient releases.
RUN apk add coreutils procps findutils wget mc htop curl netcat-openbsd bash ncurses \
    openssh-client tmux screen xz zip gzip bzip2 tar git
RUN apk add python3 || true
RUN apk add openssh-server || true
RUN apk add 7zip || true
RUN apk add zstd || true
RUN apk add shadow || true

COPY added/fish-installer.sh /fish-installer.sh
ARG INSTALL_FISH=static-latest
RUN [ "${INSTALL_FISH}" = "none" ] || (export INSTALL_FISH=${INSTALL_FISH}; /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1))

# nerdlevel 3 by default, shell-pack pager
ENV LC_NERDLEVEL=3
ENV PAGER=ppage
# preset to C.UTF-8
ENV LC_ALL=C.UTF-8

COPY added/guest-startup.sh /guest-startup.sh
COPY added/td.fish /etc/fish/functions/td.fish
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
