ARG BUILD_FROM
FROM $BUILD_FROM

ARG BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get install -y \
	lsb-release gettext-base man-db xz-utils \
	htop tmux procps mc screen curl \
	less sudo

RUN apt-get install -y gpg || echo
RUN apt-get install -y libncurses6 || echo
# NOTE: use cache to run more apt-get lines during development, then
#       move them to the combined line above.

# procps is required for 'kill', which is used inside fish mc subshell

# actually, keep lists in container for now
#RUN rm -rf /var/lib/apt/lists/*

COPY added/fish-installer.sh /fish-installer.sh
RUN /fish-installer.sh

# nerdlevel 3 by default
ENV LC_NERDLEVEL 3

COPY added/guest-startup.sh /guest-startup.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
