ARG BUILD_FROM=archlinux:latest
FROM $BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
# NOTE: the arch docker image does not have C.UTF-8, but provides en_US.UTF-8
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
ENV LC_ALL=en_US.UTF-8

RUN pacman -Sy
RUN pacman --noconfirm -S gettext man-db htop tmux procps mc \
    screen curl wget less sudo ncurses openssh openbsd-netcat git python3 \
    xz zip zstd lz4 7zip

COPY added/fish-installer.sh /fish-installer.sh
ARG FISH_STATIC=no
ARG FISH_NIGHTLY=no
RUN export FISH_NIGHTLY=${FISH_NIGHTLY}; export FISH_STATIC=${FISH_STATIC}; /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1)

# nerdlevel 3 by default
ENV LC_NERDLEVEL=3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
