ARG BUILD_FROM=almalinux:latest
FROM $BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
ENV LC_ALL=C.UTF-8

RUN dnf makecache

# for packages screen, htop on rhel 8
RUN dnf -y install epel-release || true

RUN dnf install -y \
	man-db \
	htop tmux procps mc screen \
	less sudo vim git python3 gettext netcat wget \
	xz zip zstd lz4 p7zip
RUN dnf install -y curl-minimal || dnf install -y curl

# NOTE: use cache to run more apt-get lines during development, then
#       move them to the combined line above.

COPY added/fish-installer.sh /fish-installer.sh
ARG FISH_STATIC=no
ARG FISH_NIGHTLY=no
RUN export FISH_NIGHTLY=${FISH_NIGHTLY}; export FISH_STATIC=${FISH_STATIC}; /fish-installer.sh ||(less -R "/root/fish_installer.log" && exit 1)

# nerdlevel 3 by default
ENV LC_NERDLEVEL=3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
