ARG BUILD_FROM
FROM $BUILD_FROM

ARG BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
ENV LC_ALL C.UTF-8

RUN yum makecache

# for htop on centos:
RUN yum -y install epel-release || echo

RUN yum install -y \
	man-db \
	htop tmux procps mc screen curl \
	less sudo
RUN yum install -y \
	redhat-lsb-core xz gettext

# NOTE: use cache to run more apt-get lines during development, then
#       move them to the combined line above.

COPY added/fish-installer.sh /fish-installer.sh
RUN /fish-installer.sh

# nerdlevel 3 by default
ENV LC_NERDLEVEL 3

COPY added/guest-startup.sh /guest-startup.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
