ARG BUILD_FROM=alpine:latest
FROM $BUILD_FROM

RUN apk add coreutils mc htop curl netcat-openbsd openssh-server bash ncurses \
    procps openssh-client tmux screen python3 wget zstd xz zip gzip bzip2 tar \
    git shadow findutils
RUN apk add 7zip || true
#RUN apk add 

COPY added/fish-installer.sh /fish-installer.sh
ARG INSTALL_FISH=static-latest
RUN [ "${INSTALL_FISH}" = "none" ] || (export INSTALL_FISH=${INSTALL_FISH}; /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1))

# nerdlevel 3 by default
ENV LC_NERDLEVEL=3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
