ARG BUILD_FROM
FROM $BUILD_FROM

ARG BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
# NOTE: the arch docker image does not have C.UTF-8, but provides en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN pacman -Sy
RUN pacman --noconfirm -S lsb-release gettext man-db xz htop tmux procps mc \
    screen curl less sudo ncurses openssh openbsd-netcat git

RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
COPY added/fish-installer.sh /fish-installer.sh
RUN /fish-installer.sh

# nerdlevel 3 by default
ENV LC_NERDLEVEL 3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
