ARG BUILD_FROM=debian:unstable
FROM $BUILD_FROM

# upgrade from LC_ALL "C" to add utf-8 support (prompt does not display glyphs otherwise)
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update || \
	# if apt-get update fails, try switching *.debian.org for archive.debian.org and remove "-updates" lines
	(sed --in-place=.bak 's/security.debian.org/archive.debian.org/g;s/deb.debian.org/archive.debian.org/g;/-updates/d' /etc/apt/sources.list && apt-get update) || \
	# as last resort, try again with the very slow snapshot archives
	(sed --regex '/snapshot/!s/^/#/g;/snapshot/s/^# ?//g' /etc/apt/sources.list.bak > /etc/apt/sources.list && apt-get update)
RUN apt-get install -y \
	gettext-base man-db xz-utils \
	htop tmux procps mc screen curl wget ssh openssh-server netcat.openbsd aptitude \
	less sudo vim pv git
RUN apt-get install -y iproute2 || echo "No iproute2 available, ss and consequently 'lsports' will not work"

RUN apt-get install -y gpg || echo
RUN apt-get install -y libncurses6 || echo
RUN apt-get install -y software-properties-common || echo
# NOTE: use cache to run more apt-get lines during development, then
#       move them to the combined line above.

# procps is required for 'kill', which is used inside fish mc subshell

# actually, keep lists in container for now
#RUN rm -rf /var/lib/apt/lists/*

COPY added/fish-installer.sh /fish-installer.sh
ARG FISH_STATIC=no
ARG FISH_NIGHTLY=no
RUN export FISH_NIGHTLY=${FISH_NIGHTLY}; export FISH_STATIC=${FISH_STATIC}; /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1)

# nerdlevel 3 by default
ENV LC_NERDLEVEL=3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
