ARG BUILD_FROM=alpine:latest
FROM $BUILD_FROM

# minimum packages for installer and basic functionality
RUN apk add coreutils \
    procps wget xz gzip tar \
    findutils

# extended packages - comment out for a "survival mode" container
RUN apk add mc htop curl netcat-openbsd openssh-server bash ncurses \
    openssh-client tmux screen python3 zstd zip gzip bzip2 tar \
    git shadow

# optional packages available only in more recent distro releases
RUN apk add 7zip || true

COPY added/fish-installer.sh /fish-installer.sh
ARG INSTALL_FISH=static-latest
RUN [ "${INSTALL_FISH}" = "none" ] || (export INSTALL_FISH=${INSTALL_FISH}; /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1))

# nerdlevel 3 by default
ENV LC_NERDLEVEL=3

COPY added/guest-startup.sh /guest-startup.sh
COPY added/td.fish /etc/fish/functions/td.fish
COPY added/test-populate-qssh.sh /usr/local/bin/test-populate-qssh.sh
WORKDIR /root/Downloads
ENTRYPOINT [ "/guest-startup.sh" ]
