# shell-pack tmux.conf

# new: shell config script
# for a custom color scheme, create $HOME/.config/tmux.conf.local.sh
# with one or more functions
#   custom_colors()
#   custom_styles()
#   custom_main()
# to overwrite values, see .tmux.conf.sh for details

run-shell "'$HOME/.local/share/shell-pack/config/.tmux.conf.sh'"
