# shell-pack tmux.conf

# new: shell config script
# for a custom color scheme, create $HOME/.config/tmux.conf.local.sh
# with one or more functions
#   custom_colors()
#   custom_styles()
#   custom_main()
# to overwrite values, see .tmux.conf.sh for details

# pre-script basics
bind r source-file ~/.tmux.conf \; display "Config reloaded…"
set -qg prefix C-a
set -qg prefix2 C-b

# a note on the TERM variable:
# the initial tmux run has TERM unset for run-shell because the tmux server can technically start
# with no terminal attached. $TERM is basically always wrong here, so no more attempts are made to pass it.
# instead, the script will pull it from show-environment.
run-shell "\
	export TMUX_CONF_SH_IS_RELOAD=$(tmux show -gqv '@is-reload' 2>/dev/null); \
	[ \"\$('$HOME/.local/share/shell-pack/config/.tmux.conf.sh' 2>&1 )\" = '' ] \
	|| TMUX_FAILSAFE=1 '$HOME/.local/share/shell-pack/config/.tmux.conf.sh' \
"
