complete -c dl -f
complete -c dl -l cache -x -d 'Cache result for given expiry'
complete -c dl -l cache-allow-stale -d 'Serve stale cache entry on refetch failure'
complete -c dl -l curl -d 'Force curl backend'
complete -c dl -l wget -d 'Force wget backend'
complete -c dl -s v -l verbose -d 'Verbose output'
complete -c dl -s s -l silent -d 'Silent output'
complete -c dl -s q -l quiet -d 'Silent output'
complete -c dl -s c -l continue -d 'Resume download'
complete -c dl -l resume -d 'Resume download'
complete -c dl -s n -l no-resume -d 'Do not resume download'
complete -c dl -l new -d 'Do not resume download'
complete -c dl -l restart -d 'Do not resume download'
complete -c dl -l no-continue -d 'Do not resume download'
complete -c dl -l overwrite -d 'Do not resume download'
complete -c dl -l retry -x -d 'Number of retries'
complete -c dl -l tries -x -d 'Number of retries'
complete -c dl -s 4 -d 'Use IPv4 only'
complete -c dl -s 6 -d 'Use IPv6 only'
